### ISSUE TITLE
Merge stable features into master over the v0.2 maintenance branch

### ISSUE THREAD

**Issue by erran-r7** [rapid7/convection#105]
Today development occurs on the `v0.2` branch after the stunted development of the `v1.0/packaging` branch.

We should amend the contributing guide defined in #103 to include details about the branching/merging strategy. A new `v0.2.x-maint` branch should be created for applying hot fixes on once the next major version of convection is under development. Until a new major version is under development we should continue adding stable, non-breaking, changes to master.

**Comment by erran-r7** [comment]
@jmanero-r7 @athompson-r7 @bcall-r7 @bturner-r7 shall we start a discussion around how we want to handle this? Maybe a short call (we can post the summary here) if we can't decided directly via comments.

**Comment by erran-r7** [comment]
@eciramella-r7 FYI this is the story to track merging back into master.

**Comment by eciramella-r7** [comment]
@bturner-r7 and I took a look.  Seems like there were only a few changes in master not in the V0.2 branch.  I'm working to resolve this issue and will have a clearer understanding next week.  The goal is to close out this branch.

**Comment by erran-r7** [comment]
Resolved by https://github.com/rapid7/convection/pull/138.
