### ISSUE TITLE
Improve performance of performing diffs

### ISSUE THREAD

**Issue by erran-r7** [rapid7/convection#110]
See also #109 which is a research spike where we'll document any reasons diffs may currently be slow.

**Comment by athompson-r7** [comment]
#128 May be a solution to this, depending what you are doing.

Also see my notes about splay in #111

**Comment by erran-r7** [comment]
@bcall-r7 were this (and #109) solved by #187?

**Comment by erran-r7** [comment]
Closing due to issue age.
