### ISSUE TITLE
Research what takes performing converges so long

### ISSUE THREAD

**Issue by erran-r7** [rapid7/convection#111]

**Comment by athompson-r7** [comment]
Not to long ago we were seeing AWS api rate limit errors, so I added [splay](https://github.com/rapid7/convection/commit/efcb98d939a36388f913fd74a4747c01d853f094).  Splay adds a random sleep in each stack's converge step to mitigate this.  Splay may also be adjusted in the Cloudfile if needed.

I think #108 may help this situation greatly.

**Comment by erran-r7** [comment]
Closing due to issue age.
