### ISSUE TITLE
Fail fast on converge if stack.get returns null

### ISSUE THREAD

**Issue by erran-r7** [rapid7/convection#113]
This could also be implemented by creating a `#fetch(stack, key, default_value = nil)` method which raises an exception if no default value (defaulting to `nil` should be allowed) was provided similar to Hash. `#get` can be reimplemented as a call to this method.

Let's get some discussion going on what the desired behaviour would be:

@bturner-r7 added this to the list of general improvements so maybe he could expand on why he would like to fail fast with the current `#get` method. cc @athompson-r7 @jmanero-r7 @simonirwin-r7 @abegley-r7

**Comment by athompson-r7** [comment]
This is related to #53 which didn't end up getting merged.

**Comment by bturner-r7** [comment]
Here are my pros/cons for making `stack.get` thrown an exception (or `stack.get!` if we want to follow the rails convention):

Pros:
* I see people converging with typos or other errors where some `stack.get` is nil when they didn't expect it to be.  Failing fast would reduce churn of having to rollback failed deletes.

Cons:
* This may cause diffs to fail if converging two stacks at once where the get would work once the first stack is converged, but fails during the diff.

Maybe the solution is just to display a warning if it returns nil.
