### ISSUE TITLE
Unable to create EC2 instance with EBS block device mappings

### ISSUE THREAD

**Issue by SuperGeno** [rapid7/convection#236]
# Description

Unable to set up/configure EBS block devices within EC2 instance template. 

## Expected behavior

Should be able to set up/configure EBS block device mappings within EC2 instance template.

## Observed behavior

When EBS block store configuration is declared within the `ec2_instance` template, running a `convection diff/print_template/converge` fails with `undefined local variable or method 'config'`.

It looks like the problem is just due to using the wrong variable name (`config` vs. `ebs`) when setting up the EBS properties in `aws_ec2_block_device_mapping.rb`. 

No issue with setting up/configuring Ephemeral storage.

## Steps to Reproduce

Install version 1.0.4 of the gem and run `convection print_template` on a stack that includes `ebs` block definition within an `ec2_instance` template:

```
ec2_instance 'MyEC2Instance' do
  # some settings

  block_device do
    device_name '/dev/sdf'
    ebs do
      volume_size 30
      delete_on_termination true
    end
  end
end
```

# Stack Trace or Log Messages

<details>
<summary>Stack trace for `brief error context`</summary>
<pre>
.../convection-1.0.4/lib/convection/model/template/resource_property/aws_ec2_block_device_mapping.rb:19:in `ebs': undefined local variable or method `config' for #&lt;Convection::Model::Template::ResourceProperty::EC2BlockDeviceMapping:0x007fecd9d90468&gt;(NameError)
</pre>
</details>

**Comment by erran-r7** [comment]
@SuperGeno you can use `'convection', >= 1.1.0` in your Gemfile/gemspec for these changes.

**Comment by SuperGeno** [comment]
Thanks @erran-r7, really appreciate it!
