### ISSUE TITLE
Add support for s3_bucket_policy template to render the "Id" attribute

### ISSUE THREAD

**Issue by SuperGeno** [rapid7/convection#237]
# Description

Although "Id" is not a required attribute for an S3 bucket policy, it is an attribute of the policy that may be set (the AWS S3 bucket policy generator sets this attribute for example). 

When the "Id" attribute is supplied via the s3_bucket_policy template, it is not included as part of the rendered CloudFormation JSON payload.

## Expected behavior

When supplied, should see the "Id" attribute rendered for the `PolicyDocument` node (i.e. same level as `Version` and `Statement`)  when running `convection print_template`, e.g.:

```javascript
"MyBucketPolicy": {
    "Type": "AWS::S3::BucketPolicy",
    "Properties": {
        "Bucket": {
            "Ref": "MyBucket"
        },
        "PolicyDocument": {
            "Version": "2012-10-17",
            "Id": "My bucket policy",
            "Statement": [
                // .... statements ...
            ]
        }
    }
}
```

## Observed behavior

The "Id" attribute is not rendered out in the CloudFormation bucket policy JSON payload and thus, unable to be set by the user. 

## Steps to Reproduce

Install version 1.0.4 of the gem and run `convection print_template` on a stack that includes `id` within an `s3_bucket_policy` template:

```ruby
s3_bucket_policy 'MyBucketPolicy' do
  bucket fn_ref('MyBucket')
  id 'My bucket policy'

  allow 'allow_uploads_to_my bucket' do
    principal :AWS => '*'
    s3_resource "my-bucket", '*'
    action 's3:GetObject'
  end
end
```

**Comment by erran-r7** [comment]
@SuperGeno thanks for the super detailed ticket. Check out #246 for my proposed fix. We should add your example in as a more comprehensive spec too!

**Comment by erran-r7** [comment]
@SuperGeno you can use `'convection', >= 1.1.0` in your Gemfile/gemspec for these changes.

**Comment by SuperGeno** [comment]
Super thanks @erran-r7 and the team for the fix! Love your work!

**Comment by erran-r7** [comment]
@SuperGeno thanks for your contribution! :tada: Feel free to submit a PR in the future so we can get you even more credit (tagged you in the issues and/or commits).

The team should be more responsive as well, you submitted this  around the time of our devops team summit so seems this got lost. You can ping myself, @bcall-r7, or @rdickey-r7 who have all touched it the most recently.

If you're interested we can grant you contributor access and write some contributor guidelines if you wanted to help maintain the project.
