### ISSUE TITLE
Expose account id to Stack object

### ISSUE THREAD

**Issue by athompson-r7** [rapid7/convection#52]
There are situations that it would be useful to have the account id in the context of the template.  For example using the builtin `fn_ref('AWS::AccountId')` in the below example wouldn't work quite right.

    "arn:aws:sns:#{ stack.region }:#{ fn_ref('AWS::AccountId') }:something"

Ideally the interface would be similar to this:

        "arn:aws:sns:#{ stack.region }:#{ stack.account_id }:something"

**Comment by athompson-r7** [comment]
Not sure if there is a better way to do this, but this might work.

```ruby
iam.get_user.data.user.arn.split('::').last.split(':').first
```

**Comment by erran-r7** [comment]
@athompson-r7 couldn't we do something like the following?

```ruby
delimiter = ':'
arn_prefix = 'arn:aws:sns'
fn_join(delimiter, arn_prefix, stack.region, fn_ref('AWS::AccountId'), 'something')
```

**Comment by athompson-r7** [comment]
There are certain properties that don't support join.  I think name is one those.

**Comment by erran-r7** [comment]
@athompson-r7 `Aws::STS::Client.new(region: 'us-east-1').get_caller_identity.account` 😄

**Comment by erran-r7** [comment]
@athompson-r7 Should we close this issue now? Or do you think adding a helper method on `Convection::Control::Stack` for the account ID would be worthwhile?
