### ISSUE TITLE
Description in Gemfile should be one paragraph

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/convection#74]
The `description` attribute in the Gemfile is currently [set to the entire README](
https://github.com/rapid7/convection/blob/master/lib/convection/version.rb#L5).

This doesn't look great when the gem's published to https://rubygems.org/, since there's no support for formatted descriptions. We should rewrite the description so it's a single paragraph, similar to [what hoe does](https://rubygems.org/gems/hoe).

**Comment by eciramella-r7** [comment]
All better -> https://rubygems.org/gems/convection
