### ISSUE TITLE
S3 buckets support tagging, so should convection

### ISSUE THREAD

**Issue by eciramella-r7** [rapid7/convection#89]
Convection doesn't support tagging S3 buckets.  This would really help with cost allocation tags.

**Comment by erran-r7** [comment]
@eciramella-r7 Wasn't this resolved by @athompson-r7 in 6e29288c?

**Comment by erran-r7** [comment]
Spoke with @eciramella-r7 and @athompson-r7 about this earlier and agreed this has been resolved.
